# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

exclude: ['*.log', Gemfile*, README.md, bundle, vendor]

include: [_pages]

sass:
  sass_dir: _scss
  style: compressed

title: That's (the) Mood
# email: gi@thatsmood.com
description: >- # this means to ignore newlines until "baseurl:"
  UI/UX Designer based in London, UK. 
baseurl: "https://www.thatsmood.com/" # the subpath of your site, e.g. /blog
url: "https://www.thatsmood.com/" # the base hostname & protocol for your site, e.g. http://example.com

author_name: Ginestra Ferraro
github_username:  ginestra
linkedin_username:  ginestraferraro
twitter_username: ginez_17
show_excerpts: true

# Build settings
kramdown: {hard_wrap: true}
markdown: kramdown
plugins:
  - jekyll-feed
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
